# Generated by Django 5.2.8 on 2025-12-09 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='core.sucursal'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='compania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='core.compania'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='compania',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='core.compania'),
        ),
    ]
